### ISSUE TITLE
"Error: failed decoding" Error!?

### ISSUE THREAD

**Issue by FluffyDev2019** [nerdsupremacist/CovidQL#2]
Latest beta started to give "Error: failed decoding" for me yesterday and on my wife's iPhone the the day before.

Please fix.

Regards Roger / Sweden 

![5ADBB38D-EC2D-4AAD-BE80-5FA74E7EFF10](https://user-images.githubusercontent.com/49336613/79040508-472dc600-7be9-11ea-99b8-47bd3e3a440b.jpeg)

**Comment by nerdsupremacist** [comment]
Based on the screenshot I can see that information about your country is missing. So the decoding error probably happened there

**Comment by nerdsupremacist** [comment]
Managed to reproduce the issue with this query: 

```
{
  country(name:"Sweden") {
    name
    news {
      title
    }
  }
}
```

And this one is fine:

```
{
  country(name:"Sweden") {
    name
  }
}
```

So the problem is in the News API

**Comment by nerdsupremacist** [comment]
So the News API sometimes returns empty string instead of null on images...

So I wrote a property wrapper for it. Not the best solution but it works:

```swift
@propertyWrapper
struct EmptyStringIsNil<Value: Decodable> : Decodable {
    var wrappedValue: Value?

    init(from decoder: Decoder) throws {
        let string = try String(from: decoder)
        if string == "" {
            wrappedValue = nil
        } else {
            wrappedValue = try Optional<Value>(from: decoder)
        }
    }
}
```

**Comment by nerdsupremacist** [comment]
Change is being deployed. Should be up in about 5 mins
